name: "my" # Environment
version: "3.9"

volumes:
  plcnext:

networks:
  ## Profinet Network with layer 2 Support
  pn_vlan:
    driver: macvlan
    driver_opts:
      parent: "eth0" ## TODO Add Your NIC here!
      mode: bridge
    ipam:
      config:
        - subnet: "192.168.1.10/24" ## TODO add containers Subnet here.
          gateway: "192.168.1.1" ## TODO add containers Gateway here.
  ## Default podman network for Host communication
  podman:
    name: podman
    external: true
    driver: bridge

  ## Alternative compose managed network to be used with static IPs
  #podman-alternative:
  #  driver: bridge
  #  external: false
  #  internal: true # set true to avoid multiple GWs. only allow host communication.
  #  ipam:
  #   config:
  #    - subnet: "10.89.0.1/16"

services:
  vplcnext: #Service Name
    hostname: "vplcnextcontrol1000-x86-64"
    image: "localhost/vplcnextcontrol1000-x86-64:latest"    ## TODO: select image file to use.
    networks:
      pn_vlan:
        ipv4_address: "192.168.1.10"     ##TODO: add VPLCnext Controls IP to use for PN
        mac_address: "00:a0:de:ad:be:ef" ##TODO: Insert Unique MAC if running in Bridged mode.
        x-podman.interface_name: eth0    # Do NOT change! PN is always assigned to eth0.
      podman:
        x-podman.interface_name: eth1    # Do NOT change!
      #podman-alternative:
      #  ipv4_address: "10.89.0.10"
      #  x-podman.interface_name: eth1  # Do NOT change!
    cap_add:
      - "ALL" # Give container all capabilities and later restrict through apparmor
    systemd: always # Necessary for Virtual PLCnext Controls
    sdnotify: conmon
    x-podman.conmon-pidfile: /run/vplcnext.pid
    ulimits:
      rtprio:
        soft: -1
        hard: -1
      core:
        soft: -1
        hard: -1
      #nofile: Optional 
      #  soft: 1024
      #  hard: 100000
    mem_reservation: 500m # recommended minimal available memory
    stop_grace_period: 60s # grace period for container shutdown.
    devices:
      - /dev/fuse #Necessary for SquashFS mounts and PLCnextApp support
      - /dev/net/tun # Allow rootless networking inside container.      
    tmpfs:
      - /var/volatile:rw,nodev,mode=1777
    security_opt:
      - unmask=/proc/* #Necessary for container in container support
      - apparmor=vplcnextcontrol # use "vplcnextcontrol" profile for more security.
    volumes:
      - plcnext:/opt/plcnext
#    ports:
#      - "8080:80"
#      - "8443:443"
#      - "41100:41100" # PLCnext Engineer Remoting.
    logging:
      driver: journald
    x-podman.uidmaps: # User ID mapping. ContainerUser:HostUser:AmmountOfUIDsAvailable 
      - "0:10000:100000" # default user space
      - "100000:110000:65536" # Admin id space
      - "165536:175536:65536" # privileged id space
      - "231072:241072:65536" # app id space
    x-podman.gidmaps: # Group ID mapping. ContainerGroup:HostGroup:AmmountOfGIDsAvailable
      - "0:10000:100000" # default user space
      - "100000:110000:65536" # podman Admin id space
      - "165536:175536:65536" # podman privileged id space
      - "231072:241072:65536" # podman app id space
    sysctls:
      net.ipv4.ping_group_range: "0 1012" # allow all default Users to execute ping or send icmp. Increase range as necessary.
  
    #x-podman.cpu-set: 1,3-10 # CPU setting for multi PLC setups. Do not assign same RT CPU multiple times.
